server:
  port: 2326
  servlet:
    context-path: /api

application:
  datasource:
    read:
      jdbc-url: "jdbc:mysql://localhost:3306/aptis?useSSL=false&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true"
      username: root
      password: 1234
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      maximum-pool-size: 2
    write:
      jdbc-url: "jdbc:mysql://localhost:3306/aptis?useSSL=false&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true"
      username: root
      password: 1234
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      maximum-pool-size: 2
